### ISSUE TITLE
Program failure condition not recognized

### ISSUE THREAD

**Issue by travishumble** [ORNL-QCI/xacc-dwave#5]
When submitting a job to the D-Wave processor, there is a possibility for job failure. For example, if the total program time (number of samples * program time per sample) exceeds the maximum time allowed, then the job fails without being executed. Currently, xacc appears to wait for a job completion response even when failure has occured.

Example using the dwave-factoring code:
`./dwfactoring --dwave-embedding dw-sapi --N 21 --dwave-num-reads 10000 --dwave-anneal-time 2000`

The request is for xacc to recognize when job failure occurs and to inform the calling function that the failure has occurred.

**Comment by amccaskey** [comment]
This has been fixed. Checkout https://github.com/ORNL-QCI/xacc-dwave/blob/master/accelerator/DWAccelerator.cpp#L266
